development:
  email:
    server: mail.domain.com
    port: 25
    domain: domain.com
    authentication: login
    username: 
    password: 
    contact_recipient: 

production:
  email:
    server: mail.domain.com
    port: 25
    domain: domain.com
    authentication: login
    username:
    password:
    contact_recipient:

